export type WatchlistPriority = "Core" | "Growth" | "Explore";
export type WatchlistLayer = "Stable Core" | "Rotating Discovery";
export type WatchlistSizeTier = "Flagship" | "Established" | "Mid-Market" | "Emerging";
export type WatchlistGrowthStage = "Leader" | "Scaling" | "Steady" | "Breakout";

export type WatchlistSeed = {
  name: string;
  query: string;
  niche: string;
  topicFocus: string[];
  priority: WatchlistPriority;
  layer: WatchlistLayer;
  sizeTier: WatchlistSizeTier;
  growthStage: WatchlistGrowthStage;
  cohort: string;
};

type SeedInput = Omit<WatchlistSeed, "query"> & {
  query?: string;
};

function createSeed(input: SeedInput): WatchlistSeed {
  return {
    ...input,
    query: input.query ?? input.name,
  };
}

const stableCoreSeeds: WatchlistSeed[] = [
  createSeed({
    name: "Himalayan Institute",
    niche: "Institutional yoga and spiritual education",
    topicFocus: ["meditation", "hatha yoga", "Sri Sukta", "teacher talks"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Institutional yoga",
  }),
  createSeed({
    name: "Isha Foundation",
    niche: "Spiritual discourse and event-driven clips",
    topicFocus: ["philosophy", "inner engineering", "question-led talks"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Spiritual institutions",
  }),
  createSeed({
    name: "Art of Living",
    niche: "Meditation, wisdom, and institutional wellbeing",
    topicFocus: ["breath", "meditation", "wisdom clips"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Spiritual institutions",
  }),
  createSeed({
    name: "Sivananda Yoga",
    niche: "Traditional yoga lineage education",
    topicFocus: ["asana", "meditation", "teacher education"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Traditional yoga",
  }),
  createSeed({
    name: "Yoga With Adriene",
    niche: "High-reach yoga discovery content",
    topicFocus: ["beginner yoga", "daily yoga", "search-led yoga"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Mainstream yoga",
  }),
  createSeed({
    name: "Yoga with Kassandra",
    niche: "Search-led yoga library content",
    topicFocus: ["yin yoga", "morning yoga", "specific outcomes"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Leader",
    cohort: "Mainstream yoga",
  }),
  createSeed({
    name: "Sadhguru",
    niche: "Philosophy clips and spiritual talks",
    topicFocus: ["self-inquiry", "life questions", "short discourse"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Philosophy teachers",
  }),
  createSeed({
    name: "Vedanta Society",
    niche: "Vedanta and spiritual philosophy",
    topicFocus: ["vedanta", "scripture", "lectures"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Scripture teaching",
  }),
  createSeed({
    name: "Boho Beautiful Yoga",
    niche: "Wellness-focused yoga brand",
    topicFocus: ["travel yoga", "short yoga flows", "lifestyle spirituality"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Leader",
    cohort: "Lifestyle yoga",
  }),
  createSeed({
    name: "Fightmaster Yoga",
    niche: "Yoga education and home practice",
    topicFocus: ["vinyasa", "beginner flows", "structured classes"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Home practice yoga",
  }),
  createSeed({
    name: "BrettLarkinYoga",
    query: "Brett Larkin Yoga",
    niche: "Yoga and teacher-training content",
    topicFocus: ["kundalini", "teacher training", "breathwork"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Teacher training",
  }),
  createSeed({
    name: "SarahBethYoga",
    query: "Sarah Beth Yoga",
    niche: "Outcome-led yoga instruction",
    topicFocus: ["quick yoga", "beginner yoga", "targeted routines"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Leader",
    cohort: "Outcome yoga",
  }),
  createSeed({
    name: "Alo Yoga",
    niche: "Commercial yoga lifestyle brand",
    topicFocus: ["celebrity yoga", "short practice clips", "brand-led inspiration"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Commercial wellness",
  }),
  createSeed({
    name: "Yoga Journal",
    niche: "Yoga media and education",
    topicFocus: ["asana education", "teacher insight", "wellness explainers"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Yoga media",
  }),
  createSeed({
    name: "KinoYoga",
    query: "Kino Yoga",
    niche: "Advanced and traditional yoga education",
    topicFocus: ["ashtanga", "teacher clips", "practice tips"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Traditional yoga",
  }),
  createSeed({
    name: "Five Parks Yoga",
    niche: "Long-form yoga classes",
    topicFocus: ["full classes", "yoga for specific needs", "weekly publishing"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Mid-Market",
    growthStage: "Steady",
    cohort: "Home practice yoga",
  }),
  createSeed({
    name: "Yoga with Uliana",
    query: "Yoga with Uliana",
    niche: "Short-form yoga instruction",
    topicFocus: ["mobility", "quick sessions", "practical yoga"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Mid-Market",
    growthStage: "Scaling",
    cohort: "Short-form yoga",
  }),
  createSeed({
    name: "Travis Eliot",
    niche: "Yoga and breath-led transformation",
    topicFocus: ["power yoga", "breathwork", "retreat positioning"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Mid-Market",
    growthStage: "Steady",
    cohort: "Breath and yoga",
  }),
  createSeed({
    name: "Satvic Movement",
    niche: "Yoga lifestyle and sattvic wellness",
    topicFocus: ["food", "routine", "traditional wellness"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Scaling",
    cohort: "Ayurvedic lifestyle",
  }),
  createSeed({
    name: "Bhakti Marga",
    niche: "Devotional spirituality and mantra",
    topicFocus: ["kirtan", "guru devotion", "ritual teachings"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Devotional spirituality",
  }),
  createSeed({
    name: "Sivananda Ashram Yoga Retreat",
    niche: "Ashram lifestyle and retreat positioning",
    topicFocus: ["retreat content", "traditional yoga", "community life"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Mid-Market",
    growthStage: "Steady",
    cohort: "Retreat centers",
  }),
  createSeed({
    name: "Integral Yoga Institute",
    niche: "Traditional yoga institute content",
    topicFocus: ["meditation", "philosophy", "teacher-led talks"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Mid-Market",
    growthStage: "Steady",
    cohort: "Institutional yoga",
  }),
  createSeed({
    name: "Kripalu Center for Yoga and Health",
    niche: "Retreat and wellness education",
    topicFocus: ["retreats", "wellbeing", "institutional programming"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Retreat centers",
  }),
  createSeed({
    name: "Ananda Sangha",
    niche: "Kriya yoga and devotional teachings",
    topicFocus: ["meditation", "kriya", "community teachings"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Mid-Market",
    growthStage: "Steady",
    cohort: "Kriya traditions",
  }),
  createSeed({
    name: "Self-Realization Fellowship",
    niche: "Kriya and Paramahansa Yogananda teachings",
    topicFocus: ["meditation", "lectures", "lineage teachings"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Kriya traditions",
  }),
  createSeed({
    name: "Eckhart Tolle",
    niche: "Presence and nondual spiritual teaching",
    topicFocus: ["presence", "mindfulness", "short teaching clips"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Consciousness teachers",
  }),
  createSeed({
    name: "Mooji",
    niche: "Self-inquiry and satsang",
    topicFocus: ["satsang", "self-inquiry", "awakening"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Leader",
    cohort: "Consciousness teachers",
  }),
  createSeed({
    name: "Rupert Spira",
    niche: "Nondual philosophy",
    topicFocus: ["nonduality", "awareness", "teaching excerpts"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Consciousness teachers",
  }),
  createSeed({
    name: "Michael Singer",
    query: "Michael A. Singer",
    niche: "Consciousness and surrender teaching",
    topicFocus: ["awareness", "lectures", "life practice"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Consciousness teachers",
  }),
  createSeed({
    name: "Science and Nonduality",
    query: "Science and Nonduality",
    niche: "Consciousness interviews and talks",
    topicFocus: ["consciousness", "interviews", "thought leadership"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Mid-Market",
    growthStage: "Steady",
    cohort: "Consciousness media",
  }),
  createSeed({
    name: "Mindvalley",
    niche: "Personal growth and spiritual-wellness media",
    topicFocus: ["speaker clips", "viral hooks", "self-improvement"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Personal growth media",
  }),
  createSeed({
    name: "Gaia",
    niche: "Consciousness and spiritual media brand",
    topicFocus: ["mysticism", "wellness", "series-led discovery"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Consciousness media",
  }),
  createSeed({
    name: "Ram Dass",
    niche: "Bhakti and spiritual psychology",
    topicFocus: ["lectures", "quotes", "devotional philosophy"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Leader",
    cohort: "Legacy wisdom teachers",
  }),
  createSeed({
    name: "Be Here Now Network",
    niche: "Spiritual podcast and teacher network",
    topicFocus: ["podcasts", "teacher clips", "legacy teachings"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Spiritual podcast networks",
  }),
  createSeed({
    name: "Vedanta New York",
    query: "Vedanta New York",
    niche: "Vedanta lectures and scripture",
    topicFocus: ["scripture", "lectures", "spiritual practice"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Mid-Market",
    growthStage: "Steady",
    cohort: "Scripture teaching",
  }),
  createSeed({
    name: "Chinmaya Mission",
    niche: "Vedanta organization and scripture teaching",
    topicFocus: ["gita", "upanishads", "teacher clips"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Scripture teaching",
  }),
  createSeed({
    name: "Sathya Sai International",
    query: "Sathya Sai International",
    niche: "Devotional and service-based spirituality",
    topicFocus: ["bhajans", "discourses", "community content"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Devotional spirituality",
  }),
  createSeed({
    name: "Amritanandamayi",
    query: "Amritanandamayi",
    niche: "Bhakti, compassion, and darshan-centered content",
    topicFocus: ["devotion", "service", "ashram content"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Devotional spirituality",
  }),
  createSeed({
    name: "Brahma Kumaris",
    niche: "Meditation and spiritual lifestyle education",
    topicFocus: ["raj yoga", "meditation", "daily spiritual guidance"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Meditation institutions",
  }),
  createSeed({
    name: "Heartfulness",
    niche: "Meditation institution and practice education",
    topicFocus: ["meditation", "heart-based spirituality", "explainers"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Scaling",
    cohort: "Meditation institutions",
  }),
  createSeed({
    name: "Sahaja Yoga",
    niche: "Meditation lineage content",
    topicFocus: ["kundalini", "meditation", "subtle body"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Meditation institutions",
  }),
  createSeed({
    name: "Tara Brach",
    niche: "Meditation and compassionate psychology",
    topicFocus: ["guided meditation", "lectures", "healing"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Leader",
    cohort: "Meditation teachers",
  }),
  createSeed({
    name: "Jack Kornfield",
    niche: "Mindfulness and Buddhist teaching",
    topicFocus: ["meditation", "heart practice", "wisdom talks"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Leader",
    cohort: "Meditation teachers",
  }),
  createSeed({
    name: "Insight Timer",
    niche: "Meditation platform and teacher network",
    topicFocus: ["guided meditation", "teacher clips", "calm content"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Meditation platforms",
  }),
  createSeed({
    name: "Headspace",
    niche: "Mainstream meditation brand",
    topicFocus: ["habit building", "mental clarity", "short explainers"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Meditation platforms",
  }),
  createSeed({
    name: "Ten Percent Happier",
    niche: "Meditation media and interviews",
    topicFocus: ["teacher clips", "podcast excerpts", "accessible mindfulness"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Meditation media",
  }),
  createSeed({
    name: "Waking Up with Sam Harris",
    query: "Waking Up Sam Harris",
    niche: "Philosophy and mindfulness discussion",
    topicFocus: ["consciousness", "meditation", "debate-driven clips"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Meditation media",
  }),
  createSeed({
    name: "Mingyur Rinpoche",
    niche: "Buddhist meditation teaching",
    topicFocus: ["joyful wisdom", "meditation", "teacher clips"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Buddhist teachers",
  }),
  createSeed({
    name: "Plum Village",
    niche: "Mindfulness community and monastic teachings",
    topicFocus: ["mindfulness", "community life", "gentle instruction"],
    priority: "Core",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Leader",
    cohort: "Buddhist communities",
  }),
  createSeed({
    name: "Sravasti Abbey",
    niche: "Buddhist monastic teachings",
    topicFocus: ["dharma talks", "practice advice", "community learning"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Mid-Market",
    growthStage: "Steady",
    cohort: "Buddhist communities",
  }),
  createSeed({
    name: "Sounds True",
    niche: "Spiritual interview and wisdom publisher",
    topicFocus: ["teacher clips", "podcasts", "wisdom excerpts"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Spiritual media",
  }),
  createSeed({
    name: "Breathe and Flow",
    niche: "Yoga and breathwork for lifestyle seekers",
    topicFocus: ["yoga", "breathwork", "couples branding"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Scaling",
    cohort: "Breath and yoga",
  }),
  createSeed({
    name: "Othership",
    niche: "Breathwork and transformation brand",
    topicFocus: ["ritual", "high-energy clips", "community positioning"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Mid-Market",
    growthStage: "Scaling",
    cohort: "Breathwork",
  }),
  createSeed({
    name: "Wim Hof",
    niche: "Breath, resilience, and challenge content",
    topicFocus: ["breathwork", "cold exposure", "viral challenge framing"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Breathwork",
  }),
  createSeed({
    name: "Patrick McKeown",
    query: "Patrick McKeown",
    niche: "Breath education and performance",
    topicFocus: ["nasal breathing", "health benefits", "education"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Breathwork",
  }),
  createSeed({
    name: "Andrew Huberman",
    niche: "Science-backed wellbeing media",
    topicFocus: ["habits", "clips", "science framing"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Personal growth media",
  }),
  createSeed({
    name: "Jay Shetty",
    niche: "Spiritual self-help and motivational clips",
    topicFocus: ["short wisdom", "quotes", "podcast clips"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Personal growth media",
  }),
  createSeed({
    name: "Lewis Howes",
    niche: "Podcast-led self-improvement media",
    topicFocus: ["interviews", "clips", "transformational storytelling"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Flagship",
    growthStage: "Leader",
    cohort: "Personal growth media",
  }),
  createSeed({
    name: "On Being",
    niche: "Meaning and spirituality interviews",
    topicFocus: ["long-form conversation", "thought leaders", "wisdom excerpts"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Established",
    growthStage: "Steady",
    cohort: "Spiritual media",
  }),
  createSeed({
    name: "Buddha at the Gas Pump",
    niche: "Spiritual interview archive",
    topicFocus: ["awakening stories", "teacher interviews", "long-form content"],
    priority: "Growth",
    layer: "Stable Core",
    sizeTier: "Mid-Market",
    growthStage: "Steady",
    cohort: "Spiritual media",
  }),
];

const discoveryMatrix = [
  {
    cohort: "Guided meditation",
    niche: "Guided meditation channels for sleep, stress relief, and daily calm",
    topicFocus: ["guided meditation", "stress relief", "sleep meditation"],
    baseQuery: "guided meditation channel",
  },
  {
    cohort: "Breathwork",
    niche: "Breathwork and pranayama educators",
    topicFocus: ["pranayama", "breathwork", "nervous system"],
    baseQuery: "pranayama breathwork teacher",
  },
  {
    cohort: "Beginner yoga",
    niche: "Beginner yoga and home practice teachers",
    topicFocus: ["beginner yoga", "morning yoga", "home practice"],
    baseQuery: "beginner yoga teacher",
  },
  {
    cohort: "Hatha yoga",
    niche: "Traditional hatha and classical yoga teaching",
    topicFocus: ["hatha yoga", "traditional yoga", "practice instruction"],
    baseQuery: "hatha yoga teacher",
  },
  {
    cohort: "Yin yoga",
    niche: "Yin and slow practice channels",
    topicFocus: ["yin yoga", "deep stretch", "nervous system"],
    baseQuery: "yin yoga teacher",
  },
  {
    cohort: "Kundalini yoga",
    niche: "Kundalini and subtle-body practice educators",
    topicFocus: ["kundalini", "energy practices", "mantra"],
    baseQuery: "kundalini yoga teacher",
  },
  {
    cohort: "Scripture teaching",
    niche: "Vedanta, Gita, Upanishads, and mantra interpretation",
    topicFocus: ["scripture", "vedanta", "mantra"],
    baseQuery: "vedanta scripture teacher",
  },
  {
    cohort: "Spiritual talks",
    niche: "Question-led spiritual discourse channels",
    topicFocus: ["spiritual talks", "self inquiry", "life questions"],
    baseQuery: "spiritual talk teacher",
  },
  {
    cohort: "Devotional channels",
    niche: "Mantra, chanting, bhakti, and devotional spirituality",
    topicFocus: ["chanting", "bhakti", "mantra practice"],
    baseQuery: "mantra chanting channel",
  },
  {
    cohort: "Retreat centers",
    niche: "Retreat, ashram, and spiritual center programming",
    topicFocus: ["retreat", "ashram life", "community practice"],
    baseQuery: "spiritual retreat center channel",
  },
  {
    cohort: "Spiritual podcasts",
    niche: "Interview and podcast-style spiritual channels",
    topicFocus: ["interview clips", "podcast", "transformation stories"],
    baseQuery: "spiritual podcast channel",
  },
  {
    cohort: "Ayurvedic lifestyle",
    niche: "Ayurveda and sattvic daily-life educators",
    topicFocus: ["ayurveda", "daily routine", "holistic living"],
    baseQuery: "ayurveda lifestyle teacher",
  },
];

const discoverySegments = [
  { sizeTier: "Established" as const, growthStage: "Leader" as const, qualifier: "established" },
  { sizeTier: "Mid-Market" as const, growthStage: "Scaling" as const, qualifier: "growing" },
  { sizeTier: "Emerging" as const, growthStage: "Breakout" as const, qualifier: "emerging" },
];

const discoveryAngles = [
  { suffix: "shorts", topicAugment: "short clips" },
  { suffix: "long form", topicAugment: "long-form teaching" },
  { suffix: "youtube", topicAugment: "channel strategy" },
];

const rotatingDiscoverySeeds: WatchlistSeed[] = discoveryMatrix.flatMap((cluster) =>
  discoverySegments.flatMap((segment) =>
    discoveryAngles.map((angle) =>
      createSeed({
        name: `${cluster.cohort} ${segment.qualifier} ${angle.suffix}`,
        query: `${cluster.baseQuery} ${segment.qualifier} ${angle.suffix}`,
        niche: cluster.niche,
        topicFocus: [...cluster.topicFocus, angle.topicAugment],
        priority: segment.sizeTier === "Emerging" ? "Explore" : "Growth",
        layer: "Rotating Discovery",
        sizeTier: segment.sizeTier,
        growthStage: segment.growthStage,
        cohort: cluster.cohort,
      }),
    ),
  ),
);

const discoveryExpansionMatrix = [
  "meditation teacher",
  "mindfulness teacher",
  "yoga nidra teacher",
  "chair yoga teacher",
  "somatic breathwork teacher",
  "trauma informed yoga teacher",
  "classical yoga teacher",
  "vedic chanting teacher",
  "sri sukta teacher",
  "bhagavad gita teacher",
  "upanishad teacher",
  "nondual teacher",
  "awakening podcast",
  "spiritual interview channel",
  "retreat teacher",
  "ashram teacher",
  "kirtan channel",
  "mantra meditation channel",
  "yoga philosophy teacher",
  "daily meditation teacher",
];

const extraDiscoverySeeds: WatchlistSeed[] = discoveryExpansionMatrix.flatMap((baseQuery, index) =>
  discoverySegments.map((segment) =>
    createSeed({
      name: `Discovery cohort ${index + 1} ${segment.qualifier}`,
      query: `${baseQuery} ${segment.qualifier}`,
      niche: `Discovery coverage for ${baseQuery}`,
      topicFocus: [baseQuery, "discovery", segment.qualifier],
      priority: segment.sizeTier === "Emerging" ? "Explore" : "Growth",
      layer: "Rotating Discovery",
      sizeTier: segment.sizeTier,
      growthStage: segment.growthStage,
      cohort: "Rotating discovery",
    }),
  ),
);

export const watchlistSeeds: WatchlistSeed[] = [
  ...stableCoreSeeds,
  ...rotatingDiscoverySeeds,
  ...extraDiscoverySeeds,
];

export const watchlistUniverseStats = {
  totalSeeds: watchlistSeeds.length,
  stableCoreSeeds: stableCoreSeeds.length,
  rotatingDiscoverySeeds: rotatingDiscoverySeeds.length + extraDiscoverySeeds.length,
};

export function getActiveWatchlistSeeds(date = new Date()) {
  const dayIndex = Math.floor(date.getTime() / (1000 * 60 * 60 * 24));
  const rotatingPool = [...rotatingDiscoverySeeds, ...extraDiscoverySeeds];
  const discoveryWindow = 48;

  const activeDiscovery = Array.from({ length: Math.min(discoveryWindow, rotatingPool.length) }, (_, index) => {
    return rotatingPool[(dayIndex * discoveryWindow + index) % rotatingPool.length];
  });

  return [...stableCoreSeeds, ...activeDiscovery];
}
